package com.bettafish.flarent.ui.widgets

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.VerticalDivider
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.luminance
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.bettafish.flarent.R
import com.bettafish.flarent.models.Group
import com.bettafish.flarent.models.User
import com.bettafish.flarent.utils.relativeTime
import com.bettafish.flarent.utils.toComposeColor
import com.bettafish.flarent.utils.toFaIcon
import com.guru.fontawesomecomposelib.FaIcon
import java.time.ZonedDateTime

@Composable
fun ProfileHeader(user: User, modifier: Modifier = Modifier) {
    Column(modifier = modifier.fillMaxWidth(), verticalArrangement = Arrangement.spacedBy(12.dp)) {
        val imagePreviewer = LocalImagePreviewer.current
        Avatar(
            avatarUrl = user.avatarUrl,
            name = user.displayName,
            modifier = Modifier
                .width(64.dp)
                .height(64.dp)
                .clip(CircleShape)
                .clickable {
                    user.avatarUrl?.let {
                        imagePreviewer(listOf(it), 0)
                    }
                }
        )
        Column {
            Text(
                text = user.displayName ?: user.username ?: "",
                style = MaterialTheme.typography.titleLarge
            )
            // Hide long default IDs (random numeric generated by Flarum)
            val isDefaultId = user.username?.let { it.length >= 15 && it.all { c -> c.isDigit() } } ?: false
            if (user.displayName != null && user.username != null && !isDefaultId) {
                Text(
                    user.username!!,
                    style = MaterialTheme.typography.bodyLarge,
                    color = MaterialTheme.colorScheme.outline
                )
            }
            // Time info: online / last seen
            Row(modifier = Modifier.padding(top = 2.dp)) {
                val isOnline =
                    user.lastSeenAt?.isAfter(ZonedDateTime.now().minusMinutes(2)) ?: false
                if (isOnline) {
                    Surface(
                        shape = CircleShape,
                        modifier = Modifier
                            .padding(end = 4.dp)
                            .height(8.dp)
                            .width(8.dp)
                            .align(Alignment.CenterVertically),
                        color = "#00E600".toComposeColor()!!
                    ) { }
                }
                user.lastSeenAt?.let {
                    val text = if (isOnline) {
                        stringResource(R.string.online)
                    } else {
                        stringResource(R.string.last_seen_at, it.relativeTime)
                    }
                    Text(
                        text,
                        modifier = Modifier.padding(end = 8.dp),
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.outline
                    )
                }
                user.joinTime?.let {
                    Text(
                        stringResource(R.string.joined_at, it.relativeTime),
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.outline
                    )
                }
            }
            // Birthday on separate line
            user.birthday?.let {
                Text(
                    stringResource(R.string.birthday, it),
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.outline,
                    modifier = Modifier.padding(top = 2.dp)
                )
            }
        }

        if (user.groups?.size != 0) {
            FlowRow(
                horizontalArrangement = Arrangement.spacedBy(8.dp),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                user.groups!!.forEach {
                    GroupBadge(it)
                }
            }
        }

        Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
            val baseTextStyle = MaterialTheme.typography.bodyMedium.copy(
                platformStyle = androidx.compose.ui.text.PlatformTextStyle(
                    includeFontPadding = false
                )
            )

            val density = LocalDensity.current
            val dividerHeight = remember(baseTextStyle.fontSize, density) {
                with(density) { baseTextStyle.fontSize.toDp() }
            }

            @Composable
            fun StatItem(label: String, value: String) {
                Row(
                    horizontalArrangement = Arrangement.spacedBy(4.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        text = label,
                        color = MaterialTheme.colorScheme.outline,
                        style = baseTextStyle
                    )
                    Text(
                        text = value,
                        style = baseTextStyle,
                        fontWeight = FontWeight.SemiBold,
                    )
                }
            }

            StatItem(stringResource(R.string.followers), user.followerCount.toString())

            VerticalDivider(
                modifier = Modifier
                    .height(dividerHeight)
                    .align(Alignment.CenterVertically)
            )

            StatItem(stringResource(R.string.following), user.followingCount.toString())

            VerticalDivider(
                modifier = Modifier
                    .height(dividerHeight)
                    .align(Alignment.CenterVertically)
            )

            StatItem(stringResource(R.string.likes_received), user.points.toString())
        }
        if (!user.bio.isNullOrEmpty()) {
            Text(user.bio!!)
        }

        // Experience level (foskym/custom-levels) — compact B站-style
        user.expLevel?.let { level ->
            val percent = (user.expPercent ?: 0) / 100f
            val total = user.expTotal ?: 0

            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(top = 4.dp),
                horizontalArrangement = Arrangement.spacedBy(8.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                // Level chip — small
                Surface(
                    shape = RoundedCornerShape(4.dp),
                    color = MaterialTheme.colorScheme.primaryContainer
                ) {
                    Text(
                        text = level,
                        modifier = Modifier.padding(horizontal = 6.dp, vertical = 1.dp),
                        style = MaterialTheme.typography.labelSmall,
                        color = MaterialTheme.colorScheme.onPrimaryContainer,
                        fontWeight = FontWeight.SemiBold
                    )
                }

                // Thin progress bar
                LinearProgressIndicator(
                    progress = { percent },
                    modifier = Modifier
                        .weight(1f)
                        .height(4.dp)
                        .clip(RoundedCornerShape(2.dp)),
                    color = MaterialTheme.colorScheme.primary,
                    trackColor = MaterialTheme.colorScheme.surfaceContainerLow,
                )

                // Percentage
                Text(
                    text = "${user.expPercent ?: 0}%",
                    style = MaterialTheme.typography.labelSmall,
                    color = MaterialTheme.colorScheme.primary,
                    fontWeight = FontWeight.SemiBold
                )
            }

            // Next level hint
            user.expNext?.let { nextLevel ->
                Text(
                    text = stringResource(R.string.exp_next_level, nextLevel, user.expNextNeed ?: 0),
                    style = MaterialTheme.typography.labelSmall,
                    color = MaterialTheme.colorScheme.outline,
                    modifier = Modifier.padding(top = 2.dp)
                )
            }
        }
    }
}


@Composable
fun GroupBadge(group: Group, modifier: Modifier = Modifier) {
    val bgColor =
        remember { group.color?.toComposeColor() } ?: MaterialTheme.colorScheme.secondaryContainer
    val contentColor = remember { if (bgColor.luminance() < 0.5f) Color.White else Color.Black }
    Surface(
        color = bgColor,
        shape = CircleShape,
        modifier = modifier
    ) {
        Row(
            horizontalArrangement = Arrangement.spacedBy(8.dp),
            verticalAlignment = Alignment.CenterVertically,
            modifier = Modifier.padding(horizontal = 12.dp, vertical = 4.dp)
        ) {
            val textStyle = MaterialTheme.typography.labelMedium
            group.icon?.let {
                val density = LocalDensity.current
                val textHeightDp = with(density) { textStyle.lineHeight.toDp() }
                val icon = it.toFaIcon()
                if (icon != null) {
                    FaIcon(icon, size = textHeightDp, tint = contentColor)
                }
            }

            Text(
                text = group.nameSingular ?: "",
                style = textStyle,
                color = contentColor
            )
        }
    }
}

@Preview
@Composable
fun GroupBadgePreview() {
    GroupBadge(Group().apply {
        nameSingular = "Admin"
        color = "#3A75EE"
        icon = "fas fa-wrench"
    })
}

@Preview(showBackground = true)
@Composable
fun ProfileHeaderPreview() {
    ProfileHeader(User().apply {
        displayName = "Betta_Fish"
        username = "zxbmmmmmmmmm"
        id = "1"
        joinTime = ZonedDateTime.now()
        lastSeenAt = ZonedDateTime.now()
        followerCount = 11
        followingCount = 4
        points = 514
        bio = "This user has not written anything yet."
        groups = listOf(
            Group().apply {
                nameSingular = "Admin"
                color = "#3A75EE"
                icon = "fas fa-wrench"
            },
            Group().apply {
                nameSingular = "User"
                color = "#763D99"
                icon = "fas fa-bolt"
            })
    })
}
